apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: data-writer
  namespace: default
spec:
  containers:
    - name: writer
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "Important data written at $(date)" > /data/important-file.txt
          echo "More data here" > /data/another-file.txt
          echo "Data written successfully!"
          sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-data
